added images
quarkuslab/honey-museum pull request #4
Opened 2024-08-22 10:36 UTC by adheeb2

2024-08-25 15:17 UTC, ihsanhere requested changes

2024-08-25 15:17 UTC, ihsanhere commented on .github/CODEOWNERS
remove adheeb bcz only code owners can access

2024-08-25 15:17 UTC, ihsanhere commented on src/pages/index.astro
remove script tag as it is not needed

2024-08-25 15:20 UTC, ihsanhere commented
use swiper for slider
try again with this code as reference

```
---
import 'swiper/css';
---

<div class="swiper">
    <div class="swiper-wrapper">
        <div class="swiper-slide">Slide 1</div>
        <div class="swiper-slide">Slide 2</div>
        <div class="swiper-slide">Slide 3</div>
    </div>
</div>

<script>
  import Swiper from 'swiper';
  const swiper = new Swiper('.swiper', {});
</script>
```

2024-08-25 17:07 UTC, adheeb2 commented on src/pages/index.astro
it is kept there for the 'know more' button, will change it later

2024-08-25 17:07 UTC, adheeb2 commented on .github/CODEOWNERS
ok

2024-08-25 17:08 UTC, adheeb2 commented
> use swiper for slider try again with this code as reference
> 
> ```
> ---
> import 'swiper/css';
> ---
> 
> <div class="swiper">
>     <div class="swiper-wrapper">
>         <div class="swiper-slide">Slide 1</div>
>         <div class="swiper-slide">Slide 2</div>
>         <div class="swiper-slide">Slide 3</div>
>     </div>
> </div>
> 
> <script>
>   import Swiper from 'swiper';
>   const swiper = new Swiper('.swiper', {});
> </script>
> ```
have done this type, still does not work

2024-08-30 08:06 UTC, ihsanhere approved these changes

2024-08-30 08:09 UTC, ihsanhere requested changes
Change static header to default non static. keep the header in only the initial yellow section of home page
(same as before)

2024-09-01 11:42 UTC, ihsanhere commented
Updated `main` branch with necessary assets
Complete needed changes to close this pull request

2024-09-04 06:49 UTC, adheeb2 commented
ok noted

2024-09-04 20:05 UTC, adheeb2 commented
still having problems with the slideshow

2024-09-04 20:06 UTC, adheeb2 commented
> ## Needed Changes
> 1. ### Change `header` to default style
>    remove fixed header style keep the header in only the initial yellow section of home page (same as before)
> 2. ### Update instagram image
>    
>    * get the image by merging from main branch
>    * set the instagram image to open in instagram
>    * [reference: open instagram from link](https://stackoverflow.com/questions/21295051/link-on-a-webpage-to-open-instagram-app)
>    * [reference: making image into link](https://www.geeksforgeeks.org/how-to-turn-an-image-into-a-link-in-html/)
> 3. ### Create reusable Product Component
>    
>    * create a reusable product component in `src/components/Product.astro`
>    * [reference: Astro components](https://docs.astro.build/en/basics/astro-components/#component-props)

ALL DONE

2024-09-05 11:30 UTC, ihsanvp commented
Merging this request for addressing new issues

2024-09-05 11:30 UTC, ihsanvp approved these changes

2024-09-05 11:32 UTC, ihsanhere approved these changes

2024-09-05 11:32 UTC, merged